# Tạo numpy array arr có giá trị từ 0-9. Hiển thị các phần tử có trong arr, xem kiểu dữ liệu và kích thước của arr. 

In [20]:
import numpy as np

arr = np.arange(10)
print("arr:",arr)
print('kieu du lieu cua arr :',arr.dtype)
print('kich thuoc cua arr la :',arr.size)

arr: [0 1 2 3 4 5 6 7 8 9]
kieu du lieu cua arr : int32
kich thuoc cua arr la : 10


# Từ array arr ở câu 1 => tạo arr_odd và arr_even. (odd: so le va even: so chan)

In [22]:
arr_odd=arr[arr % 2 !=0]
arr_even=arr[arr % 2 ==0]
print(arr_odd)
print(arr_even)

[1 3 5 7 9]
[0 2 4 6 8]


# Từ array arr ở câu 1 => tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100. 


In [29]:
for i in range(len(arr)):
      if arr[i] % 2 !=0:
            arr[i]=100
arr_update=arr
print(arr_update)

[  0 100   2 100   4 100   6 100   8 100]
