# Cho 2 array arr_a = [1,2,3,2,3,4,3,4,5,6] và arr_b = [7,2,10,2,7,4,9,4,9,8], thực hiện các yêu cầu sau : 

In [2]:
import numpy as np

arr_a =np.array([1,2,3,2,3,4,3,4,5,6])
arr_b =np.array([7,2,10,2,7,4,9,4,9,8])
print(arr_a)
print(arr_b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


# Tạo array arr_c chỉ lấy duy nhất các phần tử xuất hiện ở cả arr_a và arr_b.

In [38]:
arr_c=np.intersect1d(arr_a,arr_b)      
print(arr_c)
            
            
            

[2 4]


#  Từ arr_a và arr_b ở câu 1 => Tạo arr_d chứa các phần tử chỉ xuất hiện ở arr_a. 

In [39]:
arr_d=np.setdiff1d(arr_a,arr_b)
arr_d

array([1, 3, 5, 6])

# Cho arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16]), hãy tạo arr_f chỉ chứa các phần tử có giá trị từ 5 đến 10 của arr_e. 

In [40]:
arr_e = np.array([2, 6, 1, 9, 10, 3, 27, 8, 6, 25, 16])
arr_f=arr_e[(arr_e<=10) & (arr_e>=5)]
print('arr_f :',arr_f)          

arr_f : [ 6  9 10  8  6]
