# 1.Tạo arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1. 

In [4]:
import numpy as np
arr_zeros=np.zeros(10,dtype=int)
arr_zeros[5]=1
arr_zeros

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

# 2.Tạo arr_h có giá trị từ 10 đến 24. In danh sách các phần tử theo tứ tự đảo ngược của arr_h

In [38]:
arr_h=np.arange(10,25)
arr_h

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
arr_h[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

# 3.Cho arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]), tạo arr_l từ arr_k với các phần tử khác 0. 

In [109]:
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0])
arr_l =arr_k[arr_k !=0]
arr_l

array([1, 2, 8, 2, 1, 3, 5])

#  4.Từ arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuối array. 

In [111]:
arr_l_new=np.append(arr_l,(10,20))
arr_l_new

array([ 1,  2,  8,  2,  1,  3,  5, 10, 20])

#  5.Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index = 5. 

In [112]:
arr_l_update=np.insert(arr_l,5,100)
arr_l_update

array([  1,   2,   8,   2,   1, 100,   3,   5])

# 6. Từ array của câu 5, xóa các phần tử tại vị trí có index = 0, 1, 2. 

In [116]:
new_arr=np.delete(arr_l_update,[0,1,2])
new_arr

array([  2,   1, 100,   3,   5])