In [20]:
import numpy as np

# đọc file baseball_2D.1.txt

In [21]:
with open('baseball_2D.1.txt', 'r') as file_baseball :
      lines=file_baseball.readlines()
      

# lưu cột height và weight vào hai tệp txt

In [22]:
with open('height_1.txt','w') as height_file:
      for line in lines:
            height=line.strip().split('\t')[3]
            height_file.write(height + '\n')
            
with open('weight_1.txt','w') as weight_file:
      for line in lines:
            weight=line.strip().split('\t')[4]
            weight_file.write(weight + '\n')
            
      

# chép dữ liệu từ tập tin vào list là height, weight,

In [23]:
with open('height_1.txt','r') as height_1:
      height=[float(line.strip())for line in height_1.readlines()]   

with open('weight_1.txt','r') as weight_1:
      weight=[float(line.strip()) for line in weight_1.readlines()]
      
print(height)
print(weight)

[74.0, 74.0, 72.0, 72.0, 73.0, 69.0, 69.0, 71.0, 76.0, 71.0, 73.0, 73.0, 74.0, 74.0, 69.0, 70.0, 72.0, 73.0, 75.0, 78.0, 79.0, 76.0, 74.0, 76.0, 72.0, 71.0, 75.0, 77.0, 74.0, 73.0, 74.0, 78.0, 73.0, 75.0, 73.0, 75.0, 75.0, 74.0, 69.0, 71.0, 74.0, 73.0, 73.0, 76.0, 74.0, 74.0, 70.0, 72.0, 77.0, 74.0, 70.0, 76.0, 75.0, 73.0, 75.0, 76.0, 76.0, 78.0, 74.0, 74.0, 76.0, 77.0, 81.0, 78.0, 75.0, 77.0, 75.0, 76.0, 74.0, 72.0, 72.0, 75.0, 73.0, 73.0, 73.0, 70.0, 70.0, 70.0, 76.0, 68.0, 71.0, 72.0, 75.0, 75.0, 75.0, 75.0, 68.0, 74.0, 78.0, 71.0, 73.0, 76.0, 74.0, 74.0, 79.0, 75.0, 73.0, 76.0, 74.0, 74.0, 73.0, 72.0, 74.0, 73.0, 74.0, 72.0, 73.0, 69.0, 72.0, 73.0, 75.0, 75.0, 73.0, 72.0, 72.0, 76.0, 74.0, 72.0, 76.0, 77.0, 74.0, 77.0, 75.0, 76.0, 80.0, 74.0, 74.0, 75.0, 78.0, 73.0, 73.0, 74.0, 75.0, 76.0, 71.0, 73.0, 74.0, 76.0, 76.0, 74.0, 73.0, 74.0, 70.0, 72.0, 73.0, 73.0, 73.0, 73.0, 71.0, 74.0, 74.0, 72.0, 74.0, 71.0, 74.0, 75.0, 73.0, 75.0, 75.0, 79.0, 73.0, 75.0, 76.0, 74.0, 76.0, 78.0, 74.

# Tạo numpy array arr_height từ list height

In [24]:
arr_height=np.array(height)
arr_height


array([74., 74., 72., ..., 75., 75., 73.])

#  Tạo numpy array arr_weight từ list weight. 

In [25]:
arr_weight=np.array(weight)
arr_weight

array([180., 215., 210., ..., 205., 190., 195.])

# 3. Cho hệ số quy đổi từ inch sang m là 0.0254, tạo arr_height_m dựa trên công thức: arr_height * hệ số quy đổi. 

In [26]:
arr_height_m=arr_height[0:]*0.0254
arr_height_m

array([1.8796, 1.8796, 1.8288, ..., 1.905 , 1.905 , 1.8542])

# 4. Cho hệ số quy đổi từ pound sang kg là 0.453592, tạo arr_weight_kg dựa trên công thức: arr_weight * hệ số quy đổi

In [27]:
arr_weight_kg=arr_weight[:]* 0.453592
arr_weight_kg

array([81.64656, 97.52228, 95.25432, ..., 92.98636, 86.18248, 88.45044])

# 5. Tính BMI của arr_height_m và arr_weight_kg theo công thức BMI = Cân nặng / (Chiều cao * Chiều cao), và lưu vào arr_bmi. 

In [28]:
arr_bmi=arr_weight_kg/(arr_height_m*arr_height_m)
arr_bmi

array([23.11037639, 27.60406069, 28.48080465, ..., 25.62295933,
       23.74810865, 25.72686361])

# 6. Cho biết giá trị cân nặng ở vị trí index = 50 trong arr_weight_kg.

In [29]:
print(f'giá trị cân nặng của cầu thủ ở index=50 là :{arr_weight_kg[50]}')

giá trị cân nặng của cầu thủ ở index=50 là :88.45044


# 7. Tạo arr_height_m_100 gồm các phần tử có vị trí index từ 100 đến 110 (lấy cả index 110) trong arr_height_m. 

In [30]:
arr_height_m_100=arr_height_m[100:111]
arr_height_m_100

array([1.8542, 1.8288, 1.8796, 1.8542, 1.8796, 1.8288, 1.8542, 1.7526,
       1.8288, 1.8542, 1.905 ])

# 8. Cho biết các cầu thủ bóng chày có bmi < 21 trong arr_bmi. 

In [31]:
bmi_less_than_21 =arr_bmi[arr_bmi <21]
print("Các cầu thủ có BMI < 21:", bmi_less_than_21)

Các cầu thủ có BMI < 21: [20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


# 9.Cho biết chiều cao trung bình và cân nặng trung bình của các cầu thủ. 

In [32]:
height_tb=sum(arr_height_m)/len(arr_height_m)
print('chieu cao trung binh la:',height_tb)
weight_tb=sum(arr_weight_kg)/len(arr_weight_kg)
print('can nang trung binh la:',weight_tb)


chieu cao trung binh la: 1.8719529525653331
can nang trung binh la: 91.48463237173266


# 10. Cho biết chiều cao và cân nặng lớn nhất của các cầu thủ. 
# 11. Cho biết chiều cao và cân nặng nhỏ nhất của các cầu thủ. 

In [35]:
print('can nang lon nhat',max(arr_weight_kg))
print('can nang nho nhat:',min(arr_weight_kg))
print('chieu cao lon nhat',max(arr_height_m))
print('chieu cao nho nhat:',min(arr_height_m))

can nang lon nhat 131.54167999999999
can nang nho nhat: 68.0388
chieu cao lon nhat 2.1082
chieu cao nho nhat: 1.7018
