# 1. Tạo array arr có kích thước 3x3 với các giá trị True 

In [1]:
import numpy as np
arr = np.full((3,3),True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# 2. Cho arr_1D = np.array([0 1 2 3 4 5 6 7 8]). Tạo array 2 chiều có kích thước 3x3 từ arr_1D, và lưu vào arr_2D Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.

In [2]:
arr_1D=np.array([0,1,2,3,4,5,6,7,8])
arr_1D


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr_2D=arr_1D.reshape((3,3))
arr_2D

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Trong arr_2D, chuyển cột 1 sang cột 3 và ngược lại.

In [4]:
arr_2D[:,[0,2]]=arr_2D[:,[2,0]]
arr_2D

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# 3. Từ arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại.

In [5]:
arr_2D[[0,1],:]=arr_2D[[1,0],:]
arr_2D

array([[5, 4, 3],
       [2, 1, 0],
       [8, 7, 6]])

# 4. Từ arr_2D của câu 3, đảo ngược các dòng của arr_2D. 

In [6]:
aK=arr_2D[::-1,:]
aK

array([[8, 7, 6],
       [2, 1, 0],
       [5, 4, 3]])

#  Từ arr_2D của câu 4, đảo ngược các cột của arr_2D.

In [7]:
aK[:,::-1]

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

# 6. Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]), Kiểm tra trong array có giá trị rỗng không? 

In [8]:
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
arr_2D_null

array([[ 1.,  2.,  3.],
       [nan,  5.,  6.],
       [ 7., nan,  9.],
       [ 4.,  5.,  6.]])

#  Từ arr_2D_null của câu 6, thay thế giá trị null bằng 0. 

In [9]:
arr_2D_null[1,0]=0
arr_2D_null[2,1]=0
arr_2D_null

array([[1., 2., 3.],
       [0., 5., 6.],
       [7., 0., 9.],
       [4., 5., 6.]])